### ISSUE TITLE
Plans to add a license?

### ISSUE THREAD

**Issue by timisstrong** [zhichengg/StableToolBench#2]
Much appreciations for contributing the stable benchmark for our thriving tool-augmented LLM community!

Do you have any plans to add a license?  (As you likely already know, people cannot use your code freely unless you add a license: https://choosealicense.com/no-permission/)

Again, much appreciations for your contributions, and thank you for reading this!

**Comment by zhichengg** [comment]
Hi, thank you so much for your interest in our projects. 

I'm sorry for forgetting adding a license. I added an Apache 2.0 license just now. You can use the codes freely under the license now.

**Comment by timisstrong** [comment]
Thank you so much for adding the license!  Wish you a great weekend!
